project:
  type: website

website:
  title: "Randi Bolt"
  favicon: img/2025-bolt.png
  navbar:
    right:
      - text: "About"
        href: pages/about.qmd
      - text: "Blog"
        href: pages/blogs.qmd
      - text: "Dashboards"
        href: pages/dashboards.qmd
      - text: "Talks"
        href: pages/talks.qmd
      - icon: github
        href: https://github.com/rbolt13
      - icon: linkedin
        href: https://www.linkedin.com/in/randi-bolt/

format:
  html:
    theme: styles.scss


header-includes:
  - |
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
