project:
  type: website

website:
  title: "Randi Bolt"
  navbar:
    right:
      - text: "About"
        href: blog/about.qmd
      - text: "Blogs"
        href: blog/blogs.qmd
      - text: "Dashboards"
        href: blog/dashboards.qmd
      - text: "Talks"
        href: blog/talks.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/randi-bolt/

format:
  html:
    theme: styles.scss


header-includes:
  - |
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
