project:
  type: website

website:
  title: "Randi Bolt"
  navbar:
    right:
      - about.qmd
      - blogs.qmd
      - dashboards.qmd
      - talks.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/randi-bolt/

format:
  html:
    theme: styles.scss


header-includes:
  - |
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
