project:
  type: website

website:
  title: "Randi Bolt"
  favicon: img/2025-bolt.png
  google-analytics: "G-0Z8G9C0SFQ"
  navbar:
    right:
      - text: "Blog"
        href: blog.qmd
      - text: "Dashboards"
        href: dashboards.qmd
      - text: "Talks"
        href: talks.qmd
      - icon: github
        href: https://github.com/rbolt13
      - icon: linkedin
        href: https://www.linkedin.com/in/randi-bolt/

format:
  html:
    theme: styles.scss
    template-partials:
      - metadata.html

header-includes:
  - |
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
